### ISSUE TITLE
requirements.txt for Python scripts?

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-tests#23]
The gdbserver.py requires some non-standard Python packages, notably pexpect. Can we add a requirements.txt file to aid in automated testing with gdbserver?
@timsifive

**Comment by richardxia** [comment]
In addition, can we change the shebang line of [`gdbserver.py`](https://github.com/riscv/riscv-tests/blob/c8c14a5c4f29655465296fd8e3b2371c6899f604/debug/gdbserver.py#L1) to be `#!/usr/bin/env python`? The current value of `#!/usr/bin/python` prevents the use of `virtualenv`, since activating a virtualenv will change the path of Python to a special one within the virtualenv that ensures that packages within the virtualenv are in the load path.

`#!/usr/bin/env python` is also the standard shebang line used for Python scripts, since Python is not guaranteed to always be installed to `/usr/bin/python`: http://stackoverflow.com/a/19305076

**Comment by timsifive** [comment]
I've changed the shebang line as richardxia requested.

Megan, can you create the appropriate requirements.txt, or let me know how I can test that one I generate works?

**Comment by richardxia** [comment]
I can submit a pull request with the requirements.txt.

**Comment by mwachs5** [comment]
@richardxia we can close this right?

**Comment by richardxia** [comment]
Yes, we can close it now. I don't have permission to, though, so someone else needs to do it.
