### ISSUE TITLE
Erroneously recursive code generated for non-recursive memset() in syscalls.c with -O2

### ISSUE THREAD

**Issue by quxfred** [riscv/riscv-tests#321]
https://github.com/riscv/riscv-tests/blob/e75931826097c741f274212a49302e39ca597168/benchmarks/Makefile#L40

![image](https://user-images.githubusercontent.com/60102550/106360636-83b1e600-6311-11eb-9e15-4ef08d3a36c2.png)

Note the recursion marked in orange in above disassembly is supposed to perform the else-branch at common/syscalls.c:406. But this just causes a stack overflow. Adding  -fno-tree-loop-distribute-patterns or -ffreestanding got rid of this error. It looks having to do with a recurring GCC bug that attempts some obscure transformation on memset-like code.

See also:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56888
https://gcc.gnu.org/legacy-ml/gcc-help/2019-10/msg00060.html
https://gcc.gnu.org/legacy-ml/gcc-help/2019-10/msg00076.html

Regards,
Freddie

**Comment by aswaterman** [comment]
See
https://github.com/riscv/riscv-gcc/issues/197

**Comment by quxfred** [comment]
So this has been known for months. I'll close this issue then.

Should the work-around be in the Makefile?

**Comment by aswaterman** [comment]
It should be in the Makefile, but someone needs to take the time to figure out how to do it without being too disruptive to performance. -fno-builtin is too heavy of a hammer because it destroys dhrystone performance for other reasons. Jim’s suggestion on the ticket I linked to is probably the right answer, but that needs to be validated, by making sure that dhrystone’s use of string copy, struct copy, etc. are still inlined.

(Note the reason it hasn’t been fixed yet is that older versions of the compiler don’t exhibit this problem. Not that that fact helps with your situation, I realize.)

**Comment by aswaterman** [comment]
I’ll reopen the ticket since the problem isn’t actually fixed.

**Comment by quxfred** [comment]
Just made a quick-and-dirty patch in PR #322. Sorry I don't know how to put it under this issue.

**Comment by aswaterman** [comment]
I double-checked that the solution proposed in https://github.com/riscv/riscv-gcc/issues/197 works on older compilers, too, and it's a cleaner fix.  I'll commit that and close this issue.
